SystemUI: Remove Battery saver tile from sensitive QS tiles.
This partially reverts commit 94d864913ccd632a38b0a3e17ca22373b9308d57.

Since we are now using PE's SystemUIGoogle port, some modules that are
dependent on it have to be set back to ensure compatibility. Otherwise
our OS will crash.

--------- beginning of crash
12-20 15:24:24.382  2293  2293 E AndroidRuntime: FATAL EXCEPTION: main
12-20 15:24:24.382  2293  2293 E AndroidRuntime: Process: com.android.systemui, PID: 2293
12-20 15:24:24.382  2293  2293 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Lcom/android/systemui/qs/QSHost;Landroid/os/Looper;Landroid/os/Handler;Lcom/android/systemui/plugins/FalsingManager;Lcom/android/internal/logging/MetricsLogger;Lcom/android/systemui/plugins/statusbar/StatusBarStateController;Lcom/android/systemui/plugins/ActivityStarter;Lcom/android/systemui/qs/logging/QSLogger;Lcom/android/systemui/statusbar/policy/BatteryController;Lcom/android/systemui/util/settings/SecureSettings;)V in class Lcom/android/systemui/qs/tiles/BatterySaverTile; or its super classes (declaration of 'com.android.systemui.qs.tiles.BatterySaverTile' appears in /system_ext/priv-app/SystemUI/SystemUI.apk)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.google.android.systemui.qs.tiles.BatterySaverTileGoogle.<init>(Unknown Source:0)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.dagger.SystemUIGoogleDependencyProvider.provideBatterySaverTileGoogle(SystemUIGoogleDependencyProvider.java:374)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.dagger.SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.provideBatterySaverTileGoogle(SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.java:88)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.dagger.SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.get(SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.java:70)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.dagger.SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.get(SystemUIGoogleDependencyProvider_ProvideBatterySaverTileGoogleFactory.java:19)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.qs.tileimpl.QSFactoryImplGoogle.lambda$new$0(QSFactoryImplGoogle.java:131)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.qs.tileimpl.QSFactoryImplGoogle.$r8$lambda$K6Dxd6U-Y9-qIy6NBaP7glzbFOM(Unknown Source:0)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.qs.tileimpl.QSFactoryImplGoogle$$ExternalSyntheticLambda0.get(Unknown Source:2)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTileInternal(QSFactoryImpl.java:234)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTile(QSFactoryImpl.java:194)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at org.pixelexperience.systemui.qs.tileimpl.QSFactoryImplGoogle.createTile(QSFactoryImplGoogle.java:163)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.QSTileHost.createTile(QSTileHost.java:474)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.customize.TileQueryHelper.addCurrentAndStockTiles(TileQueryHelper.java:133)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.customize.TileQueryHelper.queryTiles(TileQueryHelper.java:95)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.customize.QSCustomizerController.show(QSCustomizerController.java:194)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelController.lambda$showEdit$1(QSPanelController.java:257)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelController.$r8$lambda$2ReEqaFn2L-4Ssi2HELzDJIE-IQ(Unknown Source:0)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelController$$ExternalSyntheticLambda1.run(Unknown Source:4)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7880)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
12-20 15:24:24.382  2293  2293 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

Signed-off-by: spezi77 <spezi7713@gmx.net>
Signed-off-by: Joey Huab <joey@evolution-x.org>